name: data_size
description: '🔟 Customizable data size (bit & byte) formatting for interfacing with the user'
version: 0.2.0
homepage: https://github.com/JonasWanke/data_size

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 7d558a4bf5d8bc5b4ed408ee0c7c2b6e4344bddb
  test: ^1.16.8
