name: data_size
description: '🔟 Customizable data size (bit & byte) formatting for interfacing with the user'
version: 0.2.0
homepage: https://github.com/JonasWanke/data_size

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 281f167123facb724d112ffc84349cf39d8f691f
  test: ^1.16.8
