name: Build, Test & Lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    container:
      image: google/dart:2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Persist current state
        uses: actions/upload-artifact@v1
        with:
          name: source
          path: .

  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    container:
      image: google/dart:2
    steps:
      - name: Checkout source
        uses: actions/download-artifact@v2
        with:
          name: source

      - name: Install dependencies
        run: pub get

      - name: Run tests
        run: pub run test

  coverage:
    name: Coverage
    needs: install
    runs-on: ubuntu-latest
    container:
      image: google/dart:2
    # TODO(JonasWanke): Re-enable when we re-add test_coverage.
    if: 'false'
    steps:
      - name: Checkout source
        uses: actions/download-artifact@v2
        with:
          name: source

      - name: Install dependencies
        run: pub get

      - name: Collect coverage
        run: pub run test_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    container:
      image: google/dart:2
    steps:
      - name: Checkout source
        uses: actions/download-artifact@v2
        with:
          name: source

      - name: Install dependencies
        run: pub get

      - name: Run linter
        run: dartanalyzer .
